# Dockerfile.dev
FROM golang:1.22.9-alpine

# 设置工作目录
WORKDIR /app

# 安装基础工具和 Air
# git 用于下载依赖，air 用于热重载
RUN apk add --no-cache git && \
    go install github.com/air-verse/air@latest

# 预先复制 go.mod 和 go.sum 并下载依赖
# 这样可以利用 Docker 缓存，加快构建速度
COPY go.mod go.sum ./
RUN go mod download

# 暴露端口
EXPOSE 8080

CMD ["air", "-c", ".air.toml"]